const {chromium}=require(process.env.PLAYWRIGHT_PATH||'playwright');
const assert=require('node:assert/strict');const fs=require('node:fs');
let testPage;
const base=process.env.TEST_URL;if(!base)throw Error('Set TEST_URL to the test deployment; this check writes TEST fixtures.');
const out=process.env.TEST_ARTIFACTS||'/tmp/community-study-qa/screenshots';fs.mkdirSync(out,{recursive:true});
(async()=>{const b=await chromium.launch({executablePath:process.env.CHROME_EXECUTABLE||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});try{
const p=await b.newPage({viewport:{width:1440,height:1000}});testPage=p;const errors=[];p.on('pageerror',e=>errors.push(e.message));
const button=name=>p.getByRole('button',{name,exact:true});const shot=async name=>{await p.waitForTimeout(180);return p.screenshot({path:out+'/'+name+'.png',fullPage:true});};
await p.goto(base+'/?lang=en');await button('Study session').click();await p.getByLabel('Anonymous participant code').fill('P900'+String(Date.now()).slice(-3));await p.getByRole('checkbox').check();await button('Start the study session').click();
await p.getByRole('heading',{name:'Before exploring',exact:true}).waitFor();await p.getByLabel('Beauty-community familiarity').selectOption('read');await p.getByLabel('Community participation frequency').selectOption('reader');await p.getByLabel('AI writing-support experience').selectOption('sometimes');await button('Open the reference and simulation').click();
await p.getByText('Case-reference screenshots from Chapter 7',{exact:true}).click();await p.locator('.rs-panel figure img').waitFor();assert(await p.locator('.rs-panel figure img').evaluate(im=>im.complete&&im.naturalWidth>0));await shot('01-fidelity-reference');await p.getByText('Case-reference screenshots from Chapter 7',{exact:true}).click();
assert.equal(await p.locator('.cg-ai:visible').count(),0);await p.locator('.cg-community-tabs').getByRole('button',{name:'Gallery',exact:true}).click();await p.locator('.cg-gallery-grid').getByRole('button').first().click();await p.locator('.cg-thread-preview').filter({hasText:'Read conversation'}).click();await button('Open member reply').click();await p.locator('.cg-community-tabs').getByRole('button',{name:'Profile',exact:true}).click();await p.getByLabel('Similarity of structure and expected community behaviour').selectOption('4');await p.getByLabel('Most noticeable mismatch (or “none noticed”)').fill('TEST: baseline impression captured, no human judgement claimed.');await button('Finish exploration and begin activity 1').click();
await button('Ask about this image').waitFor();console.log('PASS background, historical reference, AI-free gate and reset');
for(let phase=0;phase<2;phase++){
 await button('Ask about this image').click();await p.locator('.cg-anchor-image').click({position:{x:120,y:160}});await p.locator('.cg-view-ask textarea').fill('TEST: How does this detail relate to your method?');
 if(phase===0){await button('Find a useful prompt').click();await p.getByText('Why this suggestion?',{exact:true}).click();await shot('02-embedded-inputs');await button('Use as an editable draft').click();await p.locator('.cg-view-ask textarea').fill('TEST: '+await p.locator('.cg-view-ask textarea').inputValue()+' My own addition.');await p.getByText('AI helped here · inspect its reference',{exact:true}).click();}
 await button('Share my question').click();await button('Open member reply').waitFor();assert.equal(await p.locator('.cg-thread-photo .cg-pin').count(),1);
 if(phase===0){await button('Find a relevant member or thread').click();await button('Use as an editable draft').click();}
 await button('Open member reply').click();await p.locator('.cg-mentor .cg-sentence-list button').first().click();
 await button('Connect this sentence to detail 1').click();if(phase===1){await button('Bring the selected context here').click();await shot('03-separate-context');await button('Return without using it').click();}else await button('Use as an editable draft').click();
 await button('Come back with an update').click();await p.getByLabel('Choose scenario photo swatches',{exact:true}).click();await p.getByText('Open the supplied scenario card',{exact:true}).click();await p.getByLabel('A small update',{exact:true}).fill(phase===0?'TEST: Used less primer once; less pilling, cause uncertain.':'TEST: Tried a higher blush placement once in window light.');await p.getByText('Anything else someone should know?',{exact:true}).click();await p.getByLabel('Context, if useful',{exact:true}).fill('Window light; one fictional attempt.');await p.getByLabel('What is still open?',{exact:true}).fill('No comparison across people or conditions.');await button('Share my update').click();await button('Keep our story in an album').click();
 if(phase===0){await button('Help arrange my words').click();await button('Use as an editable draft').click();assert((await p.locator('.cg-view-draft textarea').inputValue()).includes('Ari'));}
 await button('Preview our album entry').click();const dlg=p.getByRole('dialog');assert.equal(await dlg.locator('.cg-pin').count(),1);assert.equal(await dlg.locator('.cg-review-block .cg-photo').count(),1);await shot('04-album-review-'+phase);await dlg.getByRole('checkbox').check();await button('Add to our album').click();await button('Pass this experience on').waitFor();assert.equal(await p.locator('.cg-view-album .cg-split .cg-pin').count(),1);await button('Pass this experience on').click();
 if(phase===0){await button('Prepare a reply with its source and limits').click();await button('Use as an editable draft').click();}else await p.getByLabel('Your reply to Jules',{exact:true}).fill('TEST: Sam offered a personal placement preference. One attempt in window light cannot establish a universal result.');
 await button('Reply with our album story').click();await button('Reflect on this activity').click();for(const [label,value] of [['What did pin 1 refer to?','The original cheek detail.'],['Who wrote the selected human sentence?',phase===0?'Ari':'Sam'],['What did AI change or add? If unused, say so.',phase===0?'It arranged my draft and retained the human quotation.':'I rejected the suggestion and wrote the content myself.'],['Which wording or publication decision remained yours?','I edited and chose to publish.']])await p.getByLabel(label,{exact:true}).fill('TEST: '+value);
 await p.getByLabel('What would you pass on, who helped, and what is still uncertain?',{exact:true}).fill('TEST verification only; sources and limitations retained.');for(const group of await p.getByRole('radiogroup').all())await group.getByRole('radio').nth(phase===0?3:7).check();if(phase===0){await p.waitForFunction(()=>{const d=JSON.parse(localStorage.getItem('common-ground-v3'));return d.study.research.reflectionDraft?.ratings?.every(v=>v==='4');});await p.reload();await button('Reflect').click();assert((await p.locator('.cg-reconstruction textarea').first().inputValue()).includes('original cheek'));assert.equal(await p.getByRole('radio',{checked:true}).count(),6);}await shot('05-reconstruction-'+phase);await button(phase===0?'Save reflection and take a break':'Continue to the transfer task').click();
 if(phase===0){await p.getByRole('heading',{name:'A short break',exact:true}).waitFor();await p.reload();await button('Begin activity 2').click();await button('Ask about this image').waitFor();}console.log('PASS phase '+(phase+1)+'; '+(phase===0?'all five AI moments':'AI rejection and independent completion')+'; optional thanks skipped');
}
await p.getByRole('heading',{name:'One more community situation',exact:true}).waitFor();await p.waitForFunction(async()=>{const entry=Object.entries(localStorage).find(([k])=>k.startsWith('sb-')&&k.endsWith('-auth-token'));if(!entry)return false;const auth=JSON.parse(entry[1]);const r=await fetch('https://viruhcmqmghbvyhflcom.supabase.co/rest/v1/study_sessions?select=completed,payload',{headers:{apikey:'sb_publishable_u4wYtvihaFDrwrDDSiBuAg_GZK06cRs',Authorization:'Bearer '+auth.access_token}});const rows=await r.json();return rows.length===1&&rows[0].payload.research.stage==='transfer'&&rows[0].completed===false;},{},{timeout:30000});await p.reload();await p.getByLabel('Your response',{exact:true}).fill('TEST: A hand swatch shows colour in one setting, not a face outcome. Lighting and body site differ.');await p.locator('.rs-anchor').click({position:{x:120,y:100}});await shot('06-transfer');await button('Continue to comparison').click();await p.getByLabel('When did assistance fit or interrupt the community activity?',{exact:true}).fill('TEST technical flow verification, no participant judgement.');await p.getByLabel('Overall preference',{exact:true}).selectOption('unsure');await button('Continue to debrief').click();await button('Finish session and open export').click();await p.getByText('Research record saved online.',{exact:true}).waitFor({timeout:30000});await shot('07-complete');
const saved=await p.evaluate(()=>JSON.parse(localStorage.getItem('common-ground-v3')));assert.equal(saved.study.research.stage,'finished');assert.equal(saved.study.responses.length,2);assert.equal(saved.study.responses[1].ratings[0],null);assert(saved.study.events.some(e=>e.type==='ai_trace_inspected'));assert(saved.study.events.some(e=>e.type==='assistance_source_inspected'));assert(saved.study.events.some(e=>e.type==='assistance_rejected'));assert(saved.study.research.transfer.anchor);assert(saved.study.responses.every(r=>!r.work.thanks));assert(!saved.study.events.some(e=>e.type==='transfer_draft_changed'));assert.equal(errors.length,0,errors.join('\n'));
// Read the cloud record using this test identity only; no service-role credentials.
const cloud=await p.evaluate(async()=>{const entry=Object.entries(localStorage).find(([k])=>k.startsWith('sb-')&&k.endsWith('-auth-token'));const auth=JSON.parse(entry[1]);const r=await fetch('https://viruhcmqmghbvyhflcom.supabase.co/rest/v1/study_sessions?select=completed,payload',{headers:{apikey:'sb_publishable_u4wYtvihaFDrwrDDSiBuAg_GZK06cRs',Authorization:'Bearer '+auth.access_token}});if(!r.ok)throw Error('Cloud read '+r.status);return r.json();});assert.equal(cloud.length,1);assert.equal(cloud[0].payload.research.stage,'finished');assert.equal(cloud[0].completed,true);assert.equal(cloud[0].payload.responses.length,2);
fs.writeFileSync(out+'/../technical-verification.json',JSON.stringify({testedAt:new Date().toISOString(),url:base,version:saved.version,phases:saved.study.responses.map(r=>({case:r.story,condition:r.mode,ratings:r.ratings,aiKinds:r.work.aiTrace.map(t=>t.kind)})),eventTypes:[...new Set(saved.study.events.map(e=>e.type))],fullStage:cloud[0].payload.research.stage,cloudCompleted:cloud[0].completed,pageErrors:errors,note:'Automated technical checks only, not participant outcomes.'},null,2));console.log('PASS Case C, comparison, debrief, JSON, cloud, refresh restoration and zero page errors');
}finally{if(testPage){await testPage.screenshot({path:'/tmp/study-ready-last.png',fullPage:true});console.log('Last UI',await testPage.locator('h1').allTextContents());console.log('Last stage',await testPage.evaluate(()=>JSON.parse(localStorage.getItem('common-ground-v3'))?.study?.research?.stage));}await b.close();}})().catch(e=>{console.error(e);process.exitCode=1});
