import {test} from 'node:test';
import assert from 'node:assert/strict';
import {VERSION,emptyWork,restore,log,publishAlbum} from '../lib/community-v3.ts';
import {startWeek,visitWeek,weekFeedback,seedPosts,threadOf} from '../lib/free-community.ts';
test('week observation has no prescribed case or activity gate',()=>{const s=startWeek('P998001','en','separate');assert.equal(s.research,undefined);assert.equal(s.week?.condition,'separate');const e=log(s,'post_opened',{actualStory:'C',threadId:'different-view'});assert.equal(e.events[0].story,'C');assert.equal(e.events[0].mode,'separate');assert.equal(e.events[0].detail.paired,false);const saved={version:VERSION,savedAt:Date.now(),lang:'en',story:'C',mode:'separate',works:{A:emptyWork(),B:emptyWork('B'),C:emptyWork('C')},study:s};assert(restore(JSON.stringify(saved)));});
test('empty feedback is accepted without being coded as a negative answer',()=>{const s=weekFeedback(startWeek('P998002','zh','embedded'),Array(6).fill(null),'  ','reference');assert.equal(s.week?.feedback[0].notes,'');assert.equal(s.week?.feedback[0].answered,false);assert.deepEqual(s.week?.feedback[0].ratings,Array(6).fill(null));});
test('repeat visits retain days, fixed condition and a seven-day boundary',()=>{const at=Date.now(),s=startWeek('P998003','en','embedded',at),a=visitWeek(s,at+100),b=visitWeek(a,at+86400000);assert.equal(a.week?.activeDays.length,1);assert.equal(b.week?.activeDays.length,2);assert.equal(b.week?.condition,'embedded');assert.equal(visitWeek(b,at+8*86400000).completed,true);});
test('custom albums cite actual participants instead of invented helpers',()=>{let w=emptyWork('A');w.updates=[{id:'u',text:'One experience',photo:'base',context:'',limits:'',at:new Date().toISOString()}];w.albumTitle='Title';w.albumDraft='Experience';w=publishAlbum(w,'A',{author:'P123',sourceIds:['community-post:123']});assert.deepEqual(w.versions[0].authors,['P123','You']);assert.deepEqual(w.versions[0].sourceIds,['community-post:123']);});
test('text and photo topics coexist; metadata separates their discussions',()=>{assert(seedPosts.some(p=>!p.photo));assert(seedPosts.some(p=>p.photo));assert.equal(threadOf({},'B'),'case:B');assert.equal(threadOf({thread_id:'new-topic'},'B'),'new-topic');});
