const {chromium}=require('/Users/seonyan/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'),assert=require('node:assert/strict'),fs=require('node:fs');
const root=process.env.TEST_URL||'http://127.0.0.1:4180',out='/Users/seonyan/Documents/ChatGPT/Thesis/evaluation/week_use';
(async()=>{const browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});const results=[],errors=[];const pass=s=>{console.log('PASS',s);results.push(s)};try{
const ctx=await browser.newContext({viewport:{width:1440,height:1000}}),p=await ctx.newPage();p.on('pageerror',e=>errors.push(e.message));await p.goto(root+'/?lang=en');await p.getByRole('button',{name:'Groups',exact:true}).click();
let release;const barrier=new Promise(r=>release=r);await p.route('**/reference/**',async r=>{await barrier;await r.continue()});await p.getByRole('button',{name:'View the case reference',exact:true}).click();await p.locator('.cg-dialog .cg-image-loading').first().waitFor();const a=await p.locator('.cg-dialog .cg-image-loading svg').first().evaluate(e=>getComputedStyle(e).animationName);assert(a.includes('spin'));await p.screenshot({path:out+'/14-loading.png'});release();await p.locator('.cg-dialog .image-ready').first().waitFor();await p.waitForTimeout(200);await p.locator('.cg-dialog').evaluate(e=>e.scrollTop=0);await p.screenshot({path:out+'/15-reference.png'});pass('reference placeholder animates, reserves dimensions, resolves to original image');await p.getByRole('button',{name:'Close',exact:true}).click();await p.unroute('**/reference/**');
let failed=true;await p.route('**/reference/web-community-home.png*',async r=>{if(failed){failed=false;await r.abort();}else await r.continue()});await p.getByRole('button',{name:'View the case reference',exact:true}).click();await p.locator('.cg-dialog .image-error').waitFor();await p.locator('.cg-dialog .image-error').getByRole('button',{name:'Retry',exact:true}).click();await p.locator('.cg-dialog .image-ready').first().waitFor();pass('failed image exposes a working retry');await p.getByRole('button',{name:'Close',exact:true}).click();
await p.getByLabel('Search posts',{exact:true}).fill('quiet reader');assert.equal(await p.locator('.fc-post-card').count(),1);await p.getByLabel('Search posts',{exact:true}).fill('');await p.getByLabel('Filter by group',{exact:true}).selectOption('B');assert.equal(await p.locator('.fc-post-card[data-post-id="case:A"]').count(),0);await p.getByLabel('Filter by group',{exact:true}).selectOption('');pass('search and group filters change visible posts');
await p.getByLabel('Save post: A little stuck. A little curious.',{exact:true}).click();await p.getByRole('button',{name:'Profile',exact:true}).click();await p.locator('.fc-saved [data-post-id="case:A"]').waitFor();pass('saved posts are accessible from profile');await p.getByRole('button',{name:'Groups',exact:true}).click();
await p.locator('[data-post-id="case:A"] .fc-post-title').click();assert.equal(await p.locator('.cg-detail-post').evaluate(e=>getComputedStyle(e).paddingLeft),'28px');await p.getByRole('button',{name:'Ask about this image',exact:true}).click();await p.locator('.cg-anchor-image').press('Enter');await p.getByRole('button',{name:'Find a useful prompt',exact:true}).click();const embedded=await p.locator('.cg-inline-assist blockquote').innerText();await p.getByRole('button',{name:'Return without using it',exact:true}).click();await p.getByRole('button',{name:'Research simulation',exact:false}).click();await p.getByLabel('Explore an assistance condition').selectOption('separate');await p.getByRole('button',{name:'Close',exact:true}).click();await p.getByRole('button',{name:'Find a useful prompt',exact:true}).click();await p.getByRole('button',{name:'Bring the selected context here',exact:true}).click();assert.equal(await p.locator('.cg-view-assistant blockquote').innerText(),embedded);await p.screenshot({path:out+'/16-separate-ai.png',fullPage:true});pass('separate and embedded conditions deliver the same editable preset');
await p.getByRole('button',{name:'Return without using it',exact:true}).click();await p.getByRole('button',{name:'View original',exact:true}).click();await p.locator('.cg-dialog .image-ready').waitFor();await p.screenshot({path:out+'/17-original.png'});await p.getByRole('button',{name:'Close',exact:true}).click();
await p.getByRole('button',{name:'Start a Conversation',exact:true}).click();await p.getByLabel('Post title',{exact:true}).fill('TEST Draft kept');await p.getByLabel('Your story or question',{exact:true}).fill('TEST My draft is not published.');await p.getByRole('button',{name:'Close',exact:true}).click();await p.reload();await p.getByRole('button',{name:'Start a Conversation',exact:true}).click();assert.equal(await p.getByLabel('Post title',{exact:true}).inputValue(),'TEST Draft kept');await p.route('**/rest/v1/comments*',r=>r.abort());await p.getByRole('button',{name:'Publish conversation',exact:true}).click();await p.locator('.cg-dialog [role=alert]').waitFor();assert.equal(await p.getByLabel('Your story or question',{exact:true}).inputValue(),'TEST My draft is not published.');pass('new-post draft persists across reload and failed submission');await p.getByRole('button',{name:'Close',exact:true}).click();await p.unroute('**/rest/v1/comments*');
for(const width of [1440,1100]){await p.setViewportSize({width,height:1000});await p.getByRole('button',{name:'Community',exact:true}).last().click();await p.locator('.fc-post-card').first().waitFor();assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await p.screenshot({path:out+'/18-home-'+width+'.png'});await p.getByRole('button',{name:'Groups',exact:true}).click();assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await p.screenshot({path:out+'/19-groups-'+width+'.png'});await p.locator('[data-post-id="case:B"] .fc-post-title').click();assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await p.screenshot({path:out+'/20-post-'+width+'.png'});pass('desktop '+width+' layout has no horizontal overflow');}
await p.getByLabel('Switch language',{exact:true}).click();await p.getByRole('button',{name:'群组',exact:true}).click();await p.screenshot({path:out+'/21-chinese-groups.png'});assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));pass('Chinese desktop navigation and spacing');assert.deepEqual(errors,[]);fs.writeFileSync(out+'/ui-results.json',JSON.stringify({url:root,results,errors,at:new Date().toISOString()},null,2));
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1});
