import {useState} from 'react';
import {ArrowRight,ArrowLeft,Check,MessageCircle,ExternalLink} from 'lucide-react';
import {Button} from './ui/button';
import {LoadingImage} from './loading-image';
import {photos,type Work} from '../lib/community-v3';
import {say,type Lang} from '../lib/community-v3';
import {type Related,type ExperienceSource,type MaterialKey,arrangeExperience,prepareHandoff} from '../lib/interaction-patterns';

export function RelatedConversations({items,lang,onOpen,onEvent}:{items:Related[];lang:Lang;onOpen:(r:Related)=>void;onEvent:(type:string,detail:Record<string,unknown>)=>void}){
 const [preview,setPreview]=useState<string|null>(null);
 return <div className="ip-related" data-interaction="route"><h3>Explore related conversations</h3><p className="cg-meta">Preset matches use discussion groups and shared topic words. People and posts are not ranked by expertise.</p>
 {!items.length&&<p>No matching discussion is available yet. You can keep browsing or ask the community directly.</p>}
 {items.map(r=><article className="ip-route-card" key={r.post.id}><div className="ip-route-heading">{r.post.photo&&<LoadingImage src={photos[r.post.photo].src} alt={say(lang,photos[r.post.photo].alt)}/>}<div><strong>{say(lang,r.post.title)}</strong><small>{r.post.author} · {r.post.seed?'Fictional seed conversation':'Member conversation'}</small></div></div><p className="ip-reason">{r.reasons.join(' · ')}</p><div className="ip-actions"><Button variant="outline" onClick={()=>{setPreview(preview===r.post.id?null:r.post.id);onEvent('route_previewed',{targetThread:r.post.id,reasons:r.reasons});}}>{preview===r.post.id?'Hide preview':'Preview discussion'}</Button><Button className="cg-primary" onClick={()=>onOpen(r)}>Open conversation <ArrowRight size={16}/></Button></div>{preview===r.post.id&&<div className="ip-route-preview"><p>{say(lang,r.post.body)}</p><small>Read the full discussion before deciding whether this experience fits. Opening it does not notify or contact its author.</small></div>}</article>)}
 </div>;
}

export function ExperienceAssembly({work,onApply,onEvent}:{work:Work;onApply:(text:string,selected:MaterialKey[])=>void;onEvent:(type:string,detail:Record<string,unknown>)=>void}){
 const u=work.updates.at(-1);const [selected,setSelected]=useState<MaterialKey[]>(['return','context','quote','limits']);
 if(!u)return <p>Write an update before arranging an experience.</p>;
 const material:{key:MaterialKey;label:string;text:string}[]=[{key:'return',label:'Your observation',text:u.text},{key:'context',label:'Conditions you supplied',text:u.context},{key:'quote',label:'Member wording · '+(work.selectedQuoteAuthor||'member'),text:work.selectedQuote},{key:'limits',label:'What is still open',text:u.limits}];
 return <div className="ip-assembly" data-interaction="album"><h3>Arrange the material you already shared</h3><p className="cg-meta">Choose what enters your draft. Empty fields remain empty; the preset adds no result or agreement.</p><div className="ip-assembly-grid"><div><h4>Source material</h4>{material.filter(m=>m.text).map(m=><label className="ip-material" key={m.key}><input type="checkbox" checked={selected.includes(m.key)} disabled={m.key==='return'} onChange={e=>{setSelected(old=>e.target.checked?[...old,m.key]:old.filter(k=>k!==m.key));onEvent('experience_material_selected',{material:m.key,included:e.target.checked});}}/><span><strong>{m.label}</strong><p>{m.text}</p></span></label>)}</div><div className="ip-assembly-preview"><h4>Proposed experience record</h4><p className="ip-preserved">Image reference and contributor attribution remain attached.</p><div className="ip-draft-preview">{arrangeExperience(work,selected)}</div>{!u.context&&<small>No conditions supplied. The preset will not invent them.</small>}{!u.limits&&<small>No additional limits supplied.</small>}</div></div><Button className="cg-primary" onClick={()=>onApply(arrangeExperience(work,selected),selected)}>Use this arrangement <Check size={16}/></Button><p className="cg-meta">You can edit the record and inspect its sources before publishing.</p></div>;
}

export function ExperienceComparison({sources,target,initialKey,onApply,onInspect,onEvent}:{sources:ExperienceSource[];target:string;initialKey?:string;onApply:(text:string,source:ExperienceSource,context:string)=>void;onInspect:(source:ExperienceSource)=>void;onEvent:(type:string,detail:Record<string,unknown>)=>void}){
 const [key,setKey]=useState(initialKey||sources[0]?.key||'');const [shared,setShared]=useState('');const [difference,setDifference]=useState('');
 const source=sources.find(s=>s.key===key)||sources[0];
 return <div className="ip-comparison" data-interaction="pass"><h3>Compare an experience with this conversation</h3><p className="cg-meta">A shared topic does not establish that the result will transfer. Choose a source and keep the differences visible.</p>{!source?<p>No reviewed experience is available yet. You can write an ordinary reply or keep your own experience first.</p>:<><label className="cg-field">Experience to draw on<select aria-label="Experience to draw on" value={source.key} onChange={e=>{setKey(e.target.value);onEvent('handoff_source_selected',{key:e.target.value});}}>{sources.map(s=><option value={s.key} key={s.key}>{s.album.title} · {s.author} · v{s.album.version}</option>)}</select></label><div className="ip-compare-grid"><section><h4>Earlier experience</h4><strong>{source.album.title}</strong><p>{source.album.text}</p><p className="ip-limit"><strong>Original limits</strong><br/>{source.album.limits||'No additional limits supplied.'}</p><small>{source.author} · version {source.album.version}</small><Button variant="outline" onClick={()=>onInspect(source)}>Inspect source record <ExternalLink size={15}/></Button></section><section><h4>Current conversation</h4><blockquote>{target}</blockquote><label className="cg-field">A relevant connection · optional<textarea rows={2} aria-label="A relevant connection · optional" maxLength={240} value={shared} onChange={e=>setShared(e.target.value)} placeholder="For example, the same product or technique"/></label><label className="cg-field">What may differ here · optional<textarea aria-label="What may differ here · optional" rows={3} maxLength={400} value={difference} onChange={e=>setDifference(e.target.value)} placeholder="Lighting, amount, preference, or an unknown condition"/></label></section></div><details><summary>Preview the qualified reply</summary><div className="ip-draft-preview">{prepareHandoff(source,target,shared,difference)}</div></details><Button className="cg-primary" onClick={()=>onApply(prepareHandoff(source,target,shared,difference),source,[shared,difference].filter(Boolean).join('\n'))}>Use this comparison in my reply <MessageCircle size={16}/></Button></>}</div>;
}

export function ConversationReturn({title,onReturn,onDismiss}:{title:string;onReturn:()=>void;onDismiss:()=>void}){return <div className="ip-return" role="navigation" aria-label="Conversation reference"><div><small>You arrived from</small><strong>{title}</strong></div><Button variant="outline" onClick={onReturn}><ArrowLeft size={16}/>Return to original conversation</Button><button onClick={onDismiss} aria-label="Dismiss conversation reference">×</button></div>;}
