import {LoadingImage} from './loading-image';
import {useState} from 'react';
import {Button} from './ui/button';
import {photos,clampAnchor,type Study,type Lang,type ResearchSession,type ResearchStage} from '../lib/community-v3';
import '../app/study-session.css';
const references=[
 {name:['Home','首页'],file:'web-community-home.png',date:'Justinmind · 2024',source:'https://www.justinmind.com/ui-design/tips-examples-tabs-web'},
 {name:['Conversations','讨论'],file:'web-community-conversation.png',date:'CIETY · 2023',source:'https://medium.com/@ciety/community-case-sephoras-beauty-insider-community-53dd1f79b786'},
 {name:['Gallery','图册'],file:'web-community-gallery.png',date:'CIETY · 2023',source:'https://medium.com/@ciety/community-case-sephoras-beauty-insider-community-53dd1f79b786'},
 {name:['Product topic','产品话题'],file:'web-community-product-advice.png',date:'Feedspace · accessed 2026',source:'https://www.feedspace.io/blogs/user-generated-content-examples/'}
];
export function StudySessionPanel({study,lang,onChange,onAdvance,onEvent}:{study:Study;lang:Lang;onChange:(patch:Partial<ResearchSession>,event:string,detail?:Record<string,unknown>)=>void;onAdvance:(stage:ResearchStage)=>void;onEvent:(type:string,detail?:Record<string,unknown>)=>void}){
 const [ref,setRef]=useState(0),[note,setNote]=useState(''),[level,setLevel]=useState('observation');
 const r=study.research,t=(en:string,zh:string)=>lang==='en'?en:zh;
 if(!r||r.stage==='finished')return null;
 const field=(label:string,value:string,change:(v:string)=>void,rows=3)=><label className="rs-field">{label}<textarea aria-label={label} rows={rows} maxLength={2400} value={value} placeholder={t('Optional · blank means no additional comment','可选 · 留空默认没有补充')} onChange={e=>change(e.target.value)} onBlur={()=>onEvent('research_response_reviewed',{field:label})}/></label>;
 const notes=<details className="rs-facilitator"><summary>{t('Facilitator notes','主持人记录')}</summary><p>{t('For the researcher: record observation or assistance without interpreting the participant’s answer.','供研究者使用：记录观察或提示，不在此评价参与者回答。')}</p><label className="rs-field">{t('Assistance level','提示等级')}<select value={level} onChange={e=>setLevel(e.target.value)}>{[['observation','Observation only','仅观察'],['reread-goal','Reread the goal','重读目标'],['page-region','Point to a page region','指出页面区域'],['name-control','Name the control','指出控件'],['interruption','Technical interruption','技术中断']].map(([v,en,zh])=><option key={v} value={v}>{t(en,zh)}</option>)}</select></label>{field(t('Observation','观察'),note,setNote,2)}<Button variant="outline" disabled={!note.trim()} onClick={()=>{onChange({observations:[...r.observations,{at:new Date().toISOString(),stage:r.stage,phase:study.phase,level,note:note.trim()}]},'facilitator_note',{level});setNote('');}}>{t('Save note','保存记录')}</Button><small>{r.observations.length} {t('notes saved','条记录已保存')}</small></details>;
 const next=(stage:ResearchStage,label:string,disabled=false)=><Button className="cg-primary" disabled={disabled} onClick={()=>onAdvance(stage)}>{label}</Button>;
 return <section className={'rs-panel rs-'+r.stage} aria-label={t('Research procedure','研究流程')}><div className="rs-heading"><span>{study.participant} · {t('Research session','研究会话')}</span><small>{t('Desktop Web · fictional scenarios · optional AI','桌面 Web · 虚构情境 · AI 可选')}</small></div>
 {r.stage==='background'&&<><h1>{t('Before exploring','开始探索之前')}</h1><p>{t('The facilitator will explain the study information sheet and your right to stop. Do not enter names, health information or personal photos. Screen/audio recording requires separate consent outside this website.','主持人会说明研究告知书与随时退出的权利。请勿输入姓名、健康信息或个人照片。录屏／录音须在网站之外单独征得同意。')}</p><div className="rs-grid">{([
 ['community','Beauty-community familiarity','对美妆社区的熟悉程度',[['new','New to beauty communities','不熟悉美妆社区'],['read','Have browsed a beauty community','曾浏览美妆社区'],['contribute','Have contributed to a beauty community','曾在美妆社区贡献内容'],['other','Familiar with other interest/brand communities','熟悉其他兴趣／品牌社区'],['prefer-not','Prefer not to answer','不愿回答']]],
 ['participation','Community participation frequency','社区参与频率',[['reader','Mostly read','主要阅读'],['occasional','Occasionally comment or post','偶尔评论或发帖'],['frequent','Frequently comment or post','经常评论或发帖'],['prefer-not','Prefer not to answer','不愿回答']]],
 ['aiUse','AI writing-support experience','AI 写作辅助经验',[['never','Never','从未使用'],['sometimes','Sometimes','偶尔使用'],['often','Often','经常使用'],['prefer-not','Prefer not to answer','不愿回答']]]
 ] as const).map(([key,en,zh,options])=><label key={key} className="rs-field">{t(en,zh)}<select aria-label={t(en,zh)} value={r.background[key]} onChange={e=>onChange({background:{...r.background,[key]:e.target.value}},'background_response',{field:key})}><option value="">{t('Choose one','请选择')}</option>{options.map(([v,a,b])=><option key={v} value={v}>{t(a,b)}</option>)}</select></label>)}</div>{next('fidelity',t('Open the reference and simulation','打开参照与模拟界面'),Object.values(r.background).some(v=>!v))}</>}
 {r.stage==='fidelity'&&<><h2>{t('Before AI: explore the community','使用 AI 前：探索社区')}</h2><p>{t('Review the reference pages, then explore the simulation below. Locate a photo post, a conversation, a product topic and your profile. Explain what you expected and any mismatch to the facilitator.','先看参照页面，再探索下方模拟界面。找到图片帖子、讨论、产品话题与个人档案；向主持人说明预期与不一致之处。')}</p><details onToggle={e=>{if(e.currentTarget.open)onEvent('case_reference_inspected',{surface:references[ref].name[0]});}}><summary>{t('Case-reference screenshots from Chapter 7','第七章使用的案例参照截图')}</summary><div className="rs-reference-tabs">{references.map((x,i)=><button key={x.file} aria-pressed={ref===i} onClick={()=>{setRef(i);onEvent('case_reference_inspected',{surface:x.name[0]});}}>{x.name[lang==='en'?0:1]}</button>)}</div><figure><a href={'/reference/'+references[ref].file} target="_blank" rel="noreferrer"><LoadingImage src={'/reference/'+references[ref].file} alt={t('Historical case-reference ','历史案例参照：')+references[ref].name[lang==='en'?0:1]} ratio="16 / 10"/></a><figcaption>{references[ref].date} · {t('Historical secondary-source capture; not a claim about the current service. Select image to enlarge.','历史二手来源截图，不代表当前服务；点击图片放大。')} <a href={references[ref].source} target="_blank" rel="noreferrer">{t('Source','来源')}</a></figcaption></figure></details><div className="rs-grid"><label className="rs-field">{t('Similarity of structure and expected community behaviour','结构与预期社区行为的相似程度')}<select aria-label={t('Similarity of structure and expected community behaviour','结构与预期社区行为的相似程度')} value={r.fidelity.rating} onChange={e=>onChange({fidelity:{...r.fidelity,rating:e.target.value}},'fidelity_rating')}><option value="">{t('Choose after exploring','探索后选择')}</option>{Array.from({length:7},(_,i)=><option key={i} value={i+1}>{i+1}{i===0?t(' · very different',' · 非常不同'):i===6?t(' · very similar',' · 非常相似'):''}</option>)}<option value="na">N/A</option></select></label>{field(t('Most noticeable mismatch (or “none noticed”)','最明显的不一致之处（或填写“未发现”）'),r.fidelity.mismatch,v=>onChange({fidelity:{...r.fidelity,mismatch:v}},'fidelity_comment'),2)}</div>{next('activity',t('Finish exploration and begin activity 1','结束探索，开始活动 1'),!r.fidelity.rating)}<small>{t('This records your impression; it does not automatically validate the simulation.','此处记录你的感受，不自动判定模拟界面已经有效。')}</small></>}
 {r.stage==='activity'&&<><details><summary>{t('Activity ','活动 ')+(study.phase+1)+t(' · goal reminder',' · 目标说明')}</summary><p>{t('Show what caught your eye and ask about it. Keep one part of the member reply connected to what you noticed. Record your scenario update, then prepare and review an album story. Reply to the newcomer without assuming the same result for everyone.','指出引起你注意的细节并提问；把成员回应中的一句话与观察相连；记录情境回访，准备并核对图册故事；回应新人，同时不假定所有人都会有相同结果。')}</p><p>{t('Use AI only if you want help. A thank-you is optional. You may revisit the conversation or inspect sources at any time.','仅在需要时使用 AI。感谢为可选，你可以随时回看讨论或查看来源。')}</p></details></>}
 {r.stage==='break'&&<><h1>{t('A short break','短暂休息')}</h1><p>{t('Your first activity and reflection are saved. Take 2–3 minutes if useful. The next activity has a fresh workspace and a different case.','第一组活动与反思已保存。如有需要，休息 2–3 分钟。下一组将使用全新工作区与另一案例。')}</p>{next('activity',t('Begin activity 2','开始活动 2'))}</>}
 {r.stage==='transfer'&&<><h1>{t('One more community situation','另一个社区情境')}</h1><div className="rs-transfer-content"><div><div className="rs-anchor" role="button" tabIndex={0} aria-label={t('Refer to a detail in the hand swatch image','指向手背试色图片中的细节')} onClick={e=>{const b=e.currentTarget.getBoundingClientRect();onChange({transfer:{...r.transfer,anchor:clampAnchor((e.clientX-b.left)/b.width,(e.clientY-b.top)/b.height,'swatches')}},'transfer_anchor_set');}} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();onChange({transfer:{...r.transfer,anchor:clampAnchor(.5,.5,'swatches')}},'transfer_anchor_set',{keyboard:true});}}}><img src={photos.swatches.src} alt={t('Generated hand-swatch scenario prop','生成的手背试色情境图片')}/>{r.transfer.anchor&&<span className="cg-pin" style={{left:r.transfer.anchor.x*100+'%',top:r.transfer.anchor.y*100+'%'}}>1</span>}</div><small>{t('Case C · fictional image, not product evidence','案例 C · 虚构图片，不是产品效果证据')}</small></div><div><p>{t('Lea: “A few swatches from my desk. How do you compare yours?”','Lea：“桌边留下的几笔试色，你会怎么比较？”')}</p><p><strong>{t('A newcomer asks: “Can I judge the face result from this hand swatch?”','新人问：“能从这张手背试色判断上脸效果吗？”')}</strong></p><p>{t('This hand swatch appears in one light. Explain what it can and cannot tell another member, using a visual reference if useful. No AI suggestion is provided in this task.','这张手背试色出现在一种光线下。向另一位成员说明它能与不能告诉对方什么；如有帮助，可使用视觉指代。本任务不提供 AI 建议。')}</p>{field(t('Your response','你的回应'),r.transfer.answer,v=>onChange({transfer:{...r.transfer,answer:v}},'transfer_draft_changed'),5)}<label className="rs-check"><input type="checkbox" checked={r.transfer.skipped} onChange={e=>onChange({transfer:{...r.transfer,skipped:e.target.checked}},'transfer_skip_changed')}/>{t('I prefer to skip this task','我选择跳过本任务')}</label>{next('interview',t('Continue to comparison','继续比较'),false)}</div></div></>}
 {r.stage==='interview'&&<><h1>{t('Compare the two experiences','比较两次体验')}</h1><p>{t('There are no right answers. You or the facilitator can write brief notes from your discussion. Mention moments when AI was unnecessary or uncomfortable too.','没有标准答案。你或主持人可填写讨论中的简短记录，也请提及 AI 不必要或令人不适的时刻。')}</p><div className="rs-grid">{([
 ['timing','When did assistance fit or interrupt the community activity?','辅助在何时契合或打断了社区活动？'],['references','How did the image, human reply and AI wording stay connected or become confused?','图片、成员回应与 AI 表达如何保持联系，或产生混淆？'],['culture','How did return, thanks, the album and recognition feel? Any pressure? Would you return or help again?','回访、感谢、图册与认可带来什么感受？有压力吗？愿意再次回来或帮助他人吗？'],['control','Which decisions felt yours? When was AI helpful, too powerful, weak or unnecessary?','哪些决定属于你？AI 何时有帮助、过强、过弱或多余？'],['ecosystem','Did product, profile and community-rules routes affect the community feeling?','产品、档案与社区规范入口是否影响了社区感？']
 ] as const).map(([key,en,zh])=><div key={key}>{field(t(en,zh),r.interview[key],v=>onChange({interview:{...r.interview,[key]:v}},'interview_note_changed',{theme:key}))}</div>)}</div><label className="rs-field">{t('Overall preference','总体偏好')}<select aria-label={t('Overall preference','总体偏好')} value={r.interview.preference} onChange={e=>onChange({interview:{...r.interview,preference:e.target.value}},'condition_preference')}><option value="">{t('Choose one','请选择')}</option>{[['embedded','Embedded','嵌入式'],['separate','Separate workspace','独立工作区'],['either','Either is fine','两种都可以'],['neither','Neither','两种都不喜欢'],['unsure','Unsure / no preference','不确定／无偏好']].map(([v,en,zh])=><option key={v} value={v}>{t(en,zh)}</option>)}</select></label><label className="rs-check"><input type="checkbox" checked={r.interview.skipped} onChange={e=>onChange({interview:{...r.interview,skipped:e.target.checked}},'interview_skip_changed')}/>{t('I prefer to skip the written comparison','我选择跳过书面比较')}</label>{next('debrief',t('Continue to debrief','进入结束说明'),false)}</>}
 {r.stage==='debrief'&&<><h1>{t('Before finishing','结束之前')}</h1><p>{t('AI used fixed, editable suggestions. The named members and their replies were scripted. Generated photos cannot establish beauty-product results. The two activities changed how assistance was integrated, while keeping case materials and community controls matched.','AI 使用固定且可编辑的建议。成员姓名与回应为脚本，生成图片不能证明产品效果。两组活动改变辅助的嵌入方式，同时保持案例材料与社区控件对应。')}</p><p>{t('Your private study record includes actions, artifacts, ratings and these answers. The researcher must repeat the approved withdrawal contact and deadline. Clearing this browser does not delete the online study record. Keep your participant code if requesting withdrawal.','私密研究记录包含操作、产物、评分与回答。研究者须重申已批准的退出联系方式与截止时间。清除浏览器不会删除数据库记录；申请退出时请保留参与编号。')}</p>{next('finished',t('Finish session and open export','完成会话并打开导出'))}</>}
 {notes}</section>;
}
