import {stories,VERSION,startStudy,log,type Study,type Lang,type Mode,type StoryId,type PhotoId,type Bi} from './community-v3.ts';
export type WeekStudy={protocolVersion:string;endsAt:number;condition:Mode;activeDays:string[];visits:number;lastVisitAt:number;feedback:{at:string;ratings:(number|null)[];notes:string;answered:boolean;context:string}[]};
export const localDay=(at:number)=>{const d=new Date(at);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;};
export function startWeek(participant:string,lang:Lang,condition:Mode,at=Date.now()):Study{
 const s=startStudy(participant,lang,condition==='embedded'?0:1);return {...s,version:VERSION,startedAt:at,week:{protocolVersion:'week-natural-use-2026-10-06',endsAt:at+7*86400000,condition,activeDays:[localDay(at)],visits:1,lastVisitAt:at,feedback:[]}};
}
export function visitWeek(s:Study,at=Date.now()):Study{if(!s.week||s.completed)return s;if(at>s.week.endsAt)return {...s,completed:true};const day=localDay(at);return {...log(s,'community_visit',{localDay:day}),week:{...s.week,activeDays:[...new Set([...s.week.activeDays,day])],visits:s.week.visits+1,lastVisitAt:at}};}
export function weekFeedback(s:Study,ratings:(number|null)[],notes:string,context:string):Study{if(!s.week)return s;if(ratings.length!==6||ratings.some(v=>v!==null&&(!Number.isInteger(v)||v<1||v>7)))throw Error('Invalid rating');return {...log(s,'optional_feedback_saved',{context,answered:!!notes.trim()}),week:{...s.week,feedback:[...s.week.feedback,{at:new Date().toISOString(),ratings,notes:notes.trim(),answered:!!notes.trim(),context}]}};}
export type CommunityPost={id:string;story:StoryId;title:Bi;body:Bi;author:string;photo:PhotoId|null;createdAt:string;seed:boolean};
const authored:(CommunityPost)[]=[
 {id:'primer-return',story:'A',author:'Mia',photo:'base',title:['A smaller amount, one attempt later','少一点用量，一次尝试之后'],body:['I changed just the amount of primer. The pilling seemed less noticeable once, but I cannot separate the amount from the conditions that day. Has anyone kept a useful comparison diary?','我只改变了妆前用量。一次观察中搓泥似乎少了，但无法把用量与当天条件分开。有人记录过有用的对比小记吗？']},
 {id:'first-post',story:'A',author:'Mia',photo:null,title:['A quiet reader finally saying hello','一直潜水，今天打个招呼'],body:['I usually read without posting. Seeing someone explain what they tried, including what did not change, made it easier to join. What made you feel welcome here?','我通常只阅读不发帖。看到有人连没改善的部分也分享，让我更容易参与。是什么让你觉得这里欢迎新人？']},
 {id:'brush-amount',story:'B',author:'Nora',photo:'blush',title:['Placement or amount: which do you change first?','位置还是用量：你会先改哪个？'],body:['I enjoy keeping colour near the outer cheek. When I try something new I change one detail at a time. I would love to hear your preference, rather than a rule everyone should follow.','我喜欢把颜色留在外侧面颊。尝试新画法时，我会一次只改一个细节。想听听你的偏好，而不是人人都该遵守的规则。']},
 {id:'light-notes',story:'C',author:'Lea',photo:'swatches',title:['What do you write beside a swatch photo?','试色照片旁，你会补充什么？'],body:['This desk photo is only one moment. Lighting, the amount used and the place I swatched all matter. What context do you like to keep when sharing a picture?','这张桌边照片只是一瞬间。光线、用量与试色位置都有影响。分享照片时，你习惯保留什么情境？']},
 {id:'thank-you',story:'B',author:'Nora',photo:null,title:['The small reply that made me come back','让我愿意再回来的一句回应'],body:['A member asked how the next attempt felt instead of promising a perfect result. That invitation mattered. I wanted to come back with an update, even though my experience was still uncertain.','有位成员没有保证完美结果，而是问下一次尝试感受如何。这份邀请很重要。即使还不确定，我也愿意带着近况回来。']},
 {id:'product-context',story:'A',author:'Mia',photo:null,title:['Keeping a product name with a personal experience','产品名字与个人经验放在一起'],body:['A product mention helps me understand a story, but a polished description is not evidence that it will work for me. What other context do you look for in community advice?','提到产品能帮我理解故事，但写得漂亮不等于证明它适合我。看社区建议时，你还会找什么情境？']},
 {id:'different-view',story:'C',author:'Lea',photo:'swatches',title:['A different experience is useful too','不同的经验也值得留下'],body:['If your experience differs, please add it. I would rather keep two situated accounts than turn them into one universal instruction. How would you pass that uncertainty to a newcomer?','如果你的经验不同，也欢迎补充。我宁愿保留两份有情境的经历，也不把它们变成一条通用指令。你会怎样向新人传递这份不确定？']}
].map((p,i)=>({...p,createdAt:new Date(Date.UTC(2026,9,1,12-i)).toISOString(),seed:true})) as CommunityPost[];
export const seedPosts:CommunityPost[]=[...Object.values(stories).map(s=>({id:'case:'+s.id,story:s.id,title:s.title,body:s.caption,author:s.member,photo:s.photo,createdAt:'2026-10-01T12:00:00.000Z',seed:true})),...authored];
export const groupNames:Record<StoryId,Bi>={A:['Complexion discussions','底妆讨论'],B:['Makeup techniques','彩妆技巧'],C:['Swatches and shades','试色与色号']};
export const threadOf=(metadata:Record<string,unknown>,story:StoryId)=>typeof metadata.thread_id==='string'?metadata.thread_id:'case:'+story;
